export const documentos = [
  "Admissão",
  "Alta",
  "Adminstração de Medicamentos",
  "Aspiração Oral",
  "Aspiração Traqueal (Enfermeiro)",
  "Acesso Venoso",
  "Avaliação do Nível de Consciencia",
  "Auxilio na dieta",
  "Banho de assento",
  "Balanço hidroeletrolítico pelo enfermeiro",
  "Coleta de linfa para Hanseníase",
  "Coleta de Material para o teste do Pezinho",
  "Coleta de Exame citopatológico pelo enfermeiro",
  "Condutas de segurança ao paciente",
  "Consulta de enfermagem pelo enfermeiro",
  "Contenção no leito",
  "Controle da Dor",
  "Controle hídrico",
  "Classificação de Risco",
  "Curativos",
  "Cuidados com estomas",
  "Cuidados com os pés",
  "Cuidados imediatos com o RN (Enfermeiro)",
  "Cuidados com o RN em fototerapia",
  "Cuidados com o pré-parto",
  "Cudiados no pós-parto imediato",
  "Drenagem de tórax (Enfermeiro)",
  "Drenos",
  "Diálise Peritoneal",
  "Encaminhamento para Exames, Centro Cirúrgico e Centro Obstétrico",
  "Enteróclise",
  "Exame de Montenegro",
  "Glicemia Capilar",
  "Hemodiálise",
  "Higiene do paciente - banho",
  "Higiene do couro cabeludo",
  "Higiene íntima",
  "Higiene Oral",
  "Imobilização",
  "Irrigação de Sonda vesical e bexiga",
  "Inalação / Nebulização",
  "Lavado Gástrico",
  "Massagem de conforto",
  "Medida Antropométrica",
  "Mudança de decúbito",
  "Nutrição enteral",
  "Nutrição parenteral pelo enfermeiro",
  "Óbito",
  "Ordenha mamária",
  "Punção arterial pelo enfermeiro",
  "Preparo psicológico do cliente / paciente",
  "Pressão venosa central (PVC) pelo enfermeiro",
  "Pressão arterial média (PAM) pelo enfermeiro",
  "Pré-operatório",
  "Pós-operatório imediato",
  "Pós-operatório mediato",
  "Prova do laço",
  "Registros relativos à coleta de material para exames",
  "Registros relativos à deambulação",
  "Retirada de pontos",
  "Sinais vitais",
  "Teste de PPD",
  "Teste de gravidez",
  "Teste rápido de HIV",
  "Teste rápido para Sífilis",
  "Teste para Hepatite",
  "Terapia de Reidratação Oral (TRO)",
  "Transferência interna",
  "Transferência externa",
  "Tratamento de pediculose",
  "Tratamento de miíase",
  "Transoperatório",
  "Tricotomia",
  "Vacina"
];
