export const documentos = [
  { id: 1, titulo: "Admissão" },
  { id: 2, titulo: "Alta" },
  { id: 3, titulo: "Adminstração de Medicamentos" },
  { id: 4, titulo: "Aspiração Oral" },
  { id: 5, titulo: "Aspiração Traqueal (Enfermeiro)" },
  { id: 6, titulo: "Acesso Venoso" },
  { id: 7, titulo: "Avaliação do Nível de Consciencia" },
  { id: 8, titulo: "Auxilio na dieta" },
  { id: 9, titulo: "Banho de assento" },
  { id: 10, titulo: "Balanço hidroeletrolítico pelo enfermeiro" },
  { id: 11, titulo: "Coleta de linfa para Hanseníase" },
  { id: 12, titulo: "Coleta de Material para o teste do Pezinho" },
  { id: 13, titulo: "Coleta de Exame citopatológico pelo enfermeiro" },
  { id: 14, titulo: "Condutas de segurança ao paciente" },
  { id: 15, titulo: "Consulta de enfermagem pelo enfermeiro" },
  { id: 16, titulo: "Contenção no leito" },
  { id: 17, titulo: "Controle da Dor" },
  { id: 18, titulo: "Controle hídrico" },
  { id: 19, titulo: "Classificação de Risco" },
  { id: 20, titulo: "Curativos" },
  { id: 21, titulo: "Cuidados com estomas" },
  { id: 22, titulo: "Cuidados com os pés" },
  { id: 23, titulo: "Cuidados imediatos com o RN (Enfermeiro)" },
  { id: 24, titulo: "Cuidados com o RN em fototerapia" },
  { id: 25, titulo: "Cuidados com o pré-parto" },
  { id: 26, titulo: "Cuidados no pós-parto imediato" },
  { id: 27, titulo: "Drenagem de tórax (Enfermeiro)" },
  { id: 28, titulo: "Drenos" },
  { id: 29, titulo: "Diálise Peritoneal" },
  {
    id: 30,
    titulo: "Encaminhamento para Exames, Centro Cirúrgico e Centro Obstétrico"
  },
  { id: 31, titulo: "Enteróclise" },
  { id: 32, titulo: "Exame de Montenegro" },
  { id: 33, titulo: "Glicemia Capilar" },
  { id: 34, titulo: "Hemodiálise" },
  { id: 35, titulo: "Higiene do paciente - banho" },
  { id: 36, titulo: "Higiene do couro cabeludo" },
  { id: 37, titulo: "Higiene íntima" },
  { id: 38, titulo: "Higiene Oral" },
  { id: 39, titulo: "Imobilização" },
  { id: 40, titulo: "Irrigação de Sonda vesical e bexiga" },
  { id: 41, titulo: "Inalação / Nebulização" },
  { id: 42, titulo: "Lavado Gástrico" },
  { id: 43, titulo: "Massagem de conforto" },
  { id: 44, titulo: "Medida Antropométrica" },
  { id: 45, titulo: "Mudança de decúbito" },
  { id: 46, titulo: "Nutrição enteral" },
  { id: 47, titulo: "Nutrição parenteral pelo enfermeiro" },
  { id: 48, titulo: "Óbito" },
  { id: 49, titulo: "Ordenha mamária" },
  { id: 50, titulo: "Punção arterial pelo enfermeiro" },
  { id: 51, titulo: "Preparo psicológico do cliente / paciente" },
  { id: 52, titulo: "Pressão venosa central (PVC) pelo enfermeiro" },
  { id: 53, titulo: "Pressão arterial média (PAM) pelo enfermeiro" },
  { id: 54, titulo: "Pré-operatório" },
  { id: 55, titulo: "Pós-operatório imediato" },
  { id: 56, titulo: "Prova do laço" },
  { id: 57, titulo: "Registros relativos à coleta de material para exames" },
  { id: 58, titulo: "Registros relativos à deambulação" },
  { id: 59, titulo: "Retirada de pontos" },
  { id: 60, titulo: "Sinais vitais" },
  { id: 61, titulo: "Teste de PPD" },
  { id: 62, titulo: "Teste de gravidez" },
  { id: 63, titulo: "Teste rápido de HIV" },
  { id: 64, titulo: "Teste rápido para Sífilis" },
  { id: 65, titulo: "Teste para Hepatite" },
  { id: 66, titulo: "Terapia de Reidratação Oral (TRO)" },
  { id: 67, titulo: "Transferência interna" },
  { id: 68, titulo: "Transferência externa" },
  { id: 69, titulo: "Tratamento de pediculose" },
  { id: 70, titulo: "Tratamento de miíase" },
  { id: 71, titulo: "Transoperatório" },
  { id: 72, titulo: "Tricotomia" },
  { id: 73, titulo: "Vacina" }
];
