export const GET_GLOBAL_DOCUMENTOS = "DOC/GET_GLOBAL";

export const GET_DOCUMENTO = "DOC/GET_DOCUMENTO";

export const SET_DOCUMENTO = "DOC/SET_DOCUMENTO";

export const GET_DOCUMENTOS_API = 'DOC/GET_DOCUMENTOS_API'

export const GET_TITULO_DOCUMENTOS = 'DOC/GET_TITULO_DOCUMENTOS'
